# Generated by Django 4.0.1 on 2022-01-20 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('contact_number', models.IntegerField()),
                ('books_purchased', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.book')),
            ],
        ),
    ]
