# Generated by Django 4.0.1 on 2022-01-20 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='books_purchased',
        ),
        migrations.AddField(
            model_name='customer',
            name='books_purchased',
            field=models.ManyToManyField(to='seller.Book'),
        ),
    ]
