# Generated by Django 4.0.1 on 2022-01-24 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='sold_by',
        ),
        migrations.AddField(
            model_name='book',
            name='sold_by',
            field=models.ManyToManyField(to='seller.Seller'),
        ),
    ]
